### ISSUE TITLE
I am getting error while running the code after the register page. we need to fix the API key

### ISSUE THREAD

**Issue by DmGsOuNaK** [gokberkh/SupportTicketSystem#1]
<img width="1440" alt="Screenshot 2023-07-05 at 10 23 50 AM" src="https://github.com/gokberkh/SupportTicketSystem/assets/98964768/1bfa3e4d-fcbd-4c99-9816-e725e7795b10">

**Comment by gokberkh** [comment]
In backend, you got membership from mongoDB ATLAS and changed mongoURI in server.js right? or I think it will be from process.env.SECRET_KEY in Users.js. I will deal with this issue.
